SOURCE_SHEET_NAME = "ALL INFO SHEET"
OUTPUT_SHEET_NAME = "Tendencies"
DEFENSE_SOURCE_SHEET_NAME = "WHS DATA"
DEFENSE_OUTPUT_SHEET_NAME = "DEF SELF SCOUT"
GOOGLE_CREDS_ENV = "GOOGLE_CREDS"
SPREADSHEET_ID_ENV = "SPREADSHEET_ID"

REQUIRED_COLUMNS = [
    "PLAY #","ODK","DN","DIST","HASH","YARD LN","PLAY TYPE","RESULT",
    "GN/LS","PERSONNEL","OFF FORM","BACKFIELD","MOTION","PS ALIGNMENT",
    "WS ALIGNMENT","STUD ALIGNMENT","FIB","SCHEME","OFF PLAY","PLAY DIR",
    "PLAY (STR/WK)","PZ HOLLEY","PASS PRO","READ","AWAY","COMMENTS"
]

EXPLOSIVE_RUN_YARDS = 15
EXPLOSIVE_PASS_YARDS = 20
